"""added tables and schemas

Revision ID: 56fed2ebdd69
Revises: 72a6265d89dc
Create Date: 2026-06-10 12:40:05.661173

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '56fed2ebdd69'
down_revision: Union[str, None] = '72a6265d89dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_name')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('applicant_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('resume_file', sa.Integer(), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('current_ctc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_ctc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notice_period', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resume_file'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_details_applicant_id'), 'applicant_details', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_applicant_details_id'), 'applicant_details', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hosted_by', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', name='campaign_status'), server_default='DRAFT', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hosted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_hosted_by'), 'campaigns', ['hosted_by'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('experience_required', sa.Integer(), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_posted_by'), 'jobs', ['posted_by'], unique=False)
    op.create_table('applicant_skills_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant_details.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_skills_mapping_applicant_id'), 'applicant_skills_mapping', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_applicant_skills_mapping_id'), 'applicant_skills_mapping', ['id'], unique=False)
    op.create_index(op.f('ix_applicant_skills_mapping_skill_id'), 'applicant_skills_mapping', ['skill_id'], unique=False)
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'applicant_id', name='uq_job_applicant')
    )
    op.create_index(op.f('ix_applicants_applicant_id'), 'applicants', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_applicants_id'), 'applicants', ['id'], unique=False)
    op.create_index(op.f('ix_applicants_job_id'), 'applicants', ['job_id'], unique=False)
    op.create_table('campaign_job_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('salary_min', sa.Numeric(), nullable=True),
    sa.Column('salary_max', sa.Numeric(), nullable=True),
    sa.Column('vacancies', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'job_id', name='uq_campaign_job')
    )
    op.create_index(op.f('ix_campaign_job_mapping_campaign_id'), 'campaign_job_mapping', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_job_mapping_id'), 'campaign_job_mapping', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_job_mapping_job_id'), 'campaign_job_mapping', ['job_id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('certification_title', sa.String(length=255), nullable=False),
    sa.Column('certification_expiration_date', sa.Date(), nullable=True),
    sa.Column('certification_file', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant_details.id'], ),
    sa.ForeignKeyConstraint(['certification_file'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_applicant_id'), 'certifications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_certifications_id'), 'certifications', ['id'], unique=False)
    op.create_table('job_skills_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_skills_mapping_id'), 'job_skills_mapping', ['id'], unique=False)
    op.create_index(op.f('ix_job_skills_mapping_job_id'), 'job_skills_mapping', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_skills_mapping_skill_id'), 'job_skills_mapping', ['skill_id'], unique=False)
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'password')
    op.drop_index(op.f('ix_job_skills_mapping_skill_id'), table_name='job_skills_mapping')
    op.drop_index(op.f('ix_job_skills_mapping_job_id'), table_name='job_skills_mapping')
    op.drop_index(op.f('ix_job_skills_mapping_id'), table_name='job_skills_mapping')
    op.drop_table('job_skills_mapping')
    op.drop_index(op.f('ix_certifications_id'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_applicant_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_campaign_job_mapping_job_id'), table_name='campaign_job_mapping')
    op.drop_index(op.f('ix_campaign_job_mapping_id'), table_name='campaign_job_mapping')
    op.drop_index(op.f('ix_campaign_job_mapping_campaign_id'), table_name='campaign_job_mapping')
    op.drop_table('campaign_job_mapping')
    op.drop_index(op.f('ix_applicants_job_id'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_id'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_applicant_id'), table_name='applicants')
    op.drop_table('applicants')
    op.drop_index(op.f('ix_applicant_skills_mapping_skill_id'), table_name='applicant_skills_mapping')
    op.drop_index(op.f('ix_applicant_skills_mapping_id'), table_name='applicant_skills_mapping')
    op.drop_index(op.f('ix_applicant_skills_mapping_applicant_id'), table_name='applicant_skills_mapping')
    op.drop_table('applicant_skills_mapping')
    op.drop_index(op.f('ix_jobs_posted_by'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_hosted_by'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_applicant_details_id'), table_name='applicant_details')
    op.drop_index(op.f('ix_applicant_details_applicant_id'), table_name='applicant_details')
    op.drop_table('applicant_details')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
